### ISSUE TITLE
Redirect logged-in users away from login page

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-frontend#434]
## User story

As a logged-in user, when I navigate to the login page (e.g. through a bookmark or a link in an email), I am redirected to a different page e.g. the courses page. 

This makes it clear to me that I am logged in. 

## Task
- if a user goes to /auth/login, check they are logged in
- if they are logged in redirect to the /courses page

**Comment by rabbanirizwan** [comment]
@eleanorreem 
One question is why, after a user has already logged in, the login page is still displayed to that user ?

**Comment by swetha-charles** [comment]
@rabbanirizwan 
Thanks for the comment - definitely a good alternative would be to use a guard so that logged in users can't access the page.  

If you're interestd in volunteering with us, please fill in [this form ](https://forms.gle/YPFTpjny7EWSpCHy8) and we'll get in touch to set up an onboarding call.

**Comment by PatriciaRosalis** [comment]
Hi! I'm going to pick up this issue (: When I have the branch I leave it here.

**Comment by swetha-charles** [comment]
Fixed by @PatriciaRosalis's PR
