### ISSUE TITLE
Refactor Session and Session_iba template

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-frontend#907]
### Overview
We created a duplicate but slightly different template for our IBA course. There is now a large amount of shared loginc between the regular session template and the session_iba template. 

The IBA session page can be found in `pages/courses/image-based-abuse/[sessionSlug].tsx` and the regular session page can be found in `pages/courses/[slug]/[sessionSlug].tsx`

This ticket is to pull out duplicated logic / code between the two pages into either separate components or functions that can then be shared by the two pages.

### Action Items
Here are some suggestions for possible refactors. These are suggestions and you may take a different route:
- [ ]  Extract logic which determines chat access into separate function
- [ ]  Extract logic which determines session completion into separate function
- [ ]  Create SessionHeader component which wraps around the Header component and its children
- [ ]  Create SessionVideo component to wrap around current implementation with SessionContentCard which contains Video and transcript as children
    - `callStartSession` can move into this component
    - the `useEffect` to open transcript modal can also be moved to this component
- [ ]  to handle Create Activity component to wrap around current implementation with SessionContentCard
- [ ]  Create Chat component to wrap around the current implementation of the Chat card

Testing
- [ ] Once your refactor is complete, please compare your pages to the live pages. 
- [ ] Ensure you have run cypress tests and everything still works

It may make sense to split this ticket out into separate PRs as there could be a lot of changes.

**Comment by anmol-fzr** [comment]
@eleanorreem I would like to contribute on this issue please assign me this issue

**Comment by kyleecodes** [comment]
Hey @anmol-fzr thank you for your interest!
I can assign you after [this PR](https://github.com/chaynHQ/bloom-frontend/pull/900) is either closed or completed.
As per our Issue Limit policies sometimes we have to limit the number of issues assigned to help keep a sustainable flow of issues for all contributors. Thank you!

**Comment by MarosBaran** [comment]
@kyleecodes Hi, I am a student of Technical University of Kosice (Slovakia)  and i would like to contribute on this issue as part of a task i was given on one of my subjects (i can provide details about this task in dm/pm). Can u assign me this issue if its still available?

**Comment by MarosBaran** [comment]
Hi @kyleecodes , im already working on this Issue, ive added the SessionVideo/SessionHeader components, extracted the logic for session completion, but now i have 1 question. In StoryBlokSessionPage and StoryBlokSessionIbaPage, there's a different logic for liveChatAccess, in StoryBlokSessionPage it takes into account the liveCourseAccess as well, but it doesnt in StoryBlokSessionIbaPage. Now my question is if thats intended or that it should be fixed to so that both pages share the same logic. I provide  screenshots of mentioned code, thank you for your answer.
![Screenshot 2024-10-20 at 13 54 32](https://github.com/user-attachments/assets/6c87d1a9-ea8d-4a34-84be-f6a27d7d5085)
![Screenshot 2024-10-20 at 13 54 23](https://github.com/user-attachments/assets/4a449bdf-a550-48a1-9292-b44dd59c32aa)

**Comment by kyleecodes** [comment]
@eleanorreem 

> In StoryBlokSessionPage and StoryBlokSessionIbaPage, there's a different logic for liveChatAccess, in StoryBlokSessionPage it takes into account the liveCourseAccess as well, but it doesnt in StoryBlokSessionIbaPage. Now my question is if thats intended or that it should be fixed 

Pinging @eleanorreem !

**Comment by annarhughes** [comment]
Hey @MarosBaran thanks for checking in on this `liveAccess` issue! Coincidentally I had edited this logic so that both files use the same logic. The changes are [here](https://github.com/chaynHQ/bloom-frontend/pull/1142/files#diff-c402f64820f7dd99b958c1dfca911d5df1abb2ff9b54e60b5a0a14c26e3b7119) and will be merged next week, so we may have a slight but please do continue refactoring, with both files using the same logic as you had intended to. We'll replace my change with your refactors later 👍
