### ISSUE TITLE
Add any missing properties in the message folder translation files

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-frontend#913]
### Overview
We recently had a script contributed in issue #890 . This script checks whether there are any missing translations. We have all our translations in the /messages folder. Each folder has a .json file for each language.

### Action Items

- [ ] Fix the spelling in the filename the script. The script should be checkTranslation.js rather than checkTranlation.js. You will also need to update the package.json script. Use this script and see what missing translations are there. It should tell which files to look at and which translations to create. 
- [ ] Add missing properties to the files and add the translations (use google translate for now)
- [ ] Run Cypress tests to ensure nothing is broken

**Comment by jwicksnin** [comment]
@eleanorreem Please assign this issue to me. Thanks!

**Comment by eleanorreem** [comment]
Assigned! Thanks for your interest. Let me know if you have any questions!

**Comment by jwicksnin** [comment]
Thanks! Wanted to give an update. I started on setting up the bloom backend locally but ran into an issue with Docker sadly. I spent some time debugging, and finally [opened an issue with Docker](https://github.com/docker/for-mac/issues/7294). I'm going to try a few more things and hopefully Docker will get back to me.

**Comment by jwicksnin** [comment]
I found a workaround for the Docker issue and am now moving ahead. I documented the workaround in the Docker issue in case anyone else comes across it.

**Comment by jwicksnin** [comment]
Hi @eleanorreem I'm running into some yarn/formatting issues. If I run `yarn format` without having made any code changes, it updates about twenty files with extra commas, etc. Wondering if there is a quick fix in my vscode settings that I've overlooked? I have prettier set as the default formatter and am using the recommended extensions, etc. Thanks

**Comment by kyleecodes** [comment]
Hey @jwicksnin thanks for letting us know, so sorry about this! We have implemented this pre-commit rule recently but forgot to format the project for a clean base to start with. I am fixing this right now.

For now, you can still push your changes like this:

1. Add the specific files you're changing to staging using `git add <file name>`

2. When you commit, yarn format will still run but these changes wont be added to the commit that is pushed. You can verify with `git status`.

3. You can remove those changes from yarn format locally using `git stash`. Then update your branch when the fix is ready.

**Comment by kyleecodes** [comment]
Actually @jwicksnin this problem has just been fixed! You can simply update your branch now.

**Comment by ckirby19** [comment]
Hello, I would like to pick this up :)
