### ISSUE TITLE
Improve our Open Social Sharing Preview 

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-frontend#916]
### Overview

Currently our socail share preview isn't up to scratch. We want to improve this.  When we share bloom on facebook or twitter or whatsapp we want an image and description to come up. 

### Action Items

- [ ] Add the image below to the root directory.
- [ ] Go to bloom-frontend/components/head/OpenGraphMetadata.tsx
- [ ] Update both general and twitter descriptions to be: 
_Join us on your healing journey. Bloom is here for you to learn, heal and grow towards a confident future. It is bought to you by [Chayn](https://www.chayn.co/), a global non-profit, run by survivors and allies from around the world._ 
- [ ] Test social sharing on facebook, twitter and whatsapp to see what it looks like. 

### Resources/Instructions
Image preview: 
![bloom_socials_preview](https://github.com/chaynHQ/bloom-frontend/assets/16049515/bb26e987-33e8-4557-9373-901f473e8585)

**Comment by anmol-fzr** [comment]
I would like to contribute on this issue please assign me this issue

**Comment by kyleecodes** [comment]
Hey @anmol-fzr! Thank you for your interest in contributing to Chayn.
Sorry this issue is reserved for Chayn's current open-source volunteer cohort.
We need to keep issues open for this program for the next month. You can check back in three weeks for more open issues!
Thanks again for your interest. See our [Getting Involved Guide](https://www.chayn.co/) for other ways to contribute to Chayn.

**Comment by ckirby19** [comment]
Hello, I am part of the open-source volunteer cohort and would like to work on this issue, thank you :)

**Comment by kyleecodes** [comment]
@ckirby19 you have been assigned!

**Comment by ckirby19** [comment]
Hi, I have updated the descriptions, but I am not entirely sure how social sharing can be tested locally, since I can only see previews when I use https://bloom.chayn.co/ in a twitter/facebook post. Also, the attached image was already in public/bloom_socials_preview.png, so I have only updated the description

**Comment by eleanorreem** [comment]
Hiya thanks for your contribution! I've merged your changes - thank you! I think there is a wider issue with the Open Graph Metadata setup in Bloom as the image doesn't seem to be served correctly even though it is available 😢 
<img width="238" alt="Screenshot 2024-06-04 at 19 21 03" src="https://github.com/chaynHQ/bloom-frontend/assets/16049515/134e449c-99e4-4787-be2a-298288488ba1">

I am going to write a separate issue/ bug report because it is a bigger issue than previously specified in this ticket.

I've found this [stackoverflow](https://stackoverflow.com/questions/8569892/how-to-test-open-graph-on-localhost) about how to look at Open Graph Metadata locally. Might be useful in the future!
