### ISSUE TITLE
Ensure PartnerAdminAuthguard is checking whether the admin is still active

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-frontend#917]
### Overview

We have recently created a new column for partner-admins. These partner-admins can now be set as "inactive". We need to check in our Auth guards that the partner admin is active. 

### Action Items

- [ ] Look at Partner admin auth guard bloom-frontend/guards/partnerAdminGuard.tsx
- [ ] Ensure that we are checking that the partner is active, looking at the state.partnerAdmin.active property
- [ ] Manually test that this is working by updating one of the partner admins in the database as inactive. 
- [ ] Run Cypress tests to ensure nothing is broken 

### Resources/Instructions
- to set up different user roles please look to /bloom-frontend/BLOOM_USERS.md
- You will need to know how to manually change data in the database to update user roles. Or you can use Postman and ensure you have the authentication token for Bloom. You can look how to get one of these tokens in  /bloom-frontend/CYPRESS.md

**Comment by haydnba** [comment]
I would be interested in taking this one on @eleanorreem @kyleecodes (would be very happy to manage the new dependably dependencies upgrades to familiarise myself beforehand)

**Comment by kyleecodes** [comment]
@haydnba you are assigned!

**Comment by haydnba** [comment]
Hello @eleanorreem @kyleecodes 

I have implemented this ticket and opened a PR (currently in draft). As it stands this will break in production because the data that is required to make this check is not yet being provided by the backend... In particular:

- The `PartnerAdminGuard` checks the `partnerAdmin` property of the authorised user held in state
- The ticket suggests to look "at the state.partnerAdmin.active property"
- Currently there is no such property since the backend does not yet append this data on the payload returned to the client on user authorisation

I think it is simple to remedy on Bloom Backend:
- update the interface to include `active` at `src/partner-admin/partner-admin.interface.ts`
- update the user payload formatter to include the `active` property on the appended `partnerAdmin` at `src/utils/serialize.ts`

Definitely likely I am missing something completely obvious but if not then I'd be very happy to create an issue and open the PR on Bloom Backend

**Comment by eleanorreem** [comment]
@haydnba yes you are right ! Thanks for flagging. An oversight on my part. I had thought it was already being returned! I can create a ticket on in the backend and hopefully it will be picked up soon!

**Comment by haydnba** [comment]
@eleanorreem thats great, thanks! If you're ok with it I've done the work locally to get it working so feel free to adding me on the issue and I'll open a pr

**Comment by eleanorreem** [comment]
Oh brilliant! Ahead of the game

**Comment by eleanorreem** [comment]
https://github.com/chaynHQ/bloom-backend/issues/444 can you comment on this ticket so I can assign you 😄
